version: '3'
services:
  laravel:
    image: php:8.3-fpm
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    networks:
      - blog-network
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - blog-network
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge
volumes:
  mysql-data: