services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    environment:
      - APP_URL=http://ec2-13-230-222-144.ap-northeast-1.compute.amazonaws.com
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DB_DATABASE=laravel
    depends_on:
      - mysql
    networks:
      - blog-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/out:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - blog-network
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - blog-network
volumes:
  mysql_data:
networks:
  blog-network:
    driver: bridge