# blog/docker-compose.yml
services:
  laravel:
    image: php:8.3-fpm
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=blog
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - blog-network
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - blog-network
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - blog-network
  nextjs:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge
volumes:
  mysql-data: